Don't use apache commons-codec to encode NBT Hex.
Causes NoClassDefFoundError on dedicated server.

I did test this to make sure it output the same format as old
implementation (hex with lowercase alphas).